apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: noop
        image: briankopp/noop-server:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: consumer
  labels:
    app: consumer
spec:
  selector:
    app: consumer
  ports:
  - port: 3000
  type: NodePort
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer
  namespace: consumer
  labels:
    app: consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: foobar
        selector:
          matchLabels:
            queue: bar
      target:
        averageValue: 1000
        type: AverageValue
